kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-es-config-v0.1.6
  namespace: {{ .Values.namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
      @log_level {{ .Values.logLevel }}
    </system>

  containers.input.conf: |-
    <source>
      @id fluentd-containers.log
      @type tail
      path "/var/log/containers/*.log"
      pos_file /var/log/es-containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      refresh_interval 10s
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

  forward.input.conf: |-
    # Takes the messages sent over TCP
    <source>
      @type forward
    </source>

  output.conf: |-
    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @type kubernetes_metadata
    </filter>

    # Concatenate multi-line logs
    <filter **>
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
    </filter>

    <match kubernetes.var.log.containers.**.log>
      @id elasticsearch
      @type elasticsearch
      @log_level INFO
      type_name fluentd
      include_tag_key true
      include_timestamp true
      time_key_exclude_timestamp false
      host {{ .Values.configMap.data.elasticUrl }}
      port {{ .Values.configMap.data.elasticPort }}
      scheme {{ .Values.configMap.data.scheme }}
      user {{ .Values.configMap.data.elasticUser }}
      password {{ .Values.configMap.data.elasticPass }}
      logstash_format false
      index_name k8s-logs
      <buffer tag, time>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 20
        flush_interval 5s
        retry_forever true
        retry_max_interval 30
        chunk_limit_size 10M
        queue_limit_length 8
        overflow_action block
        timekey 0.1h
      </buffer>
    </match>
